version: '3.8'
services:
    api:
        container_name: guildAPI
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./:/usr/src/app
    mongodb:
        image: mongo
        container_name: mongodbGuild
        ports:
            - 27017:27017